### ISSUE TITLE
Design and build the harness for pubsub tests

### ISSUE THREAD

**Issue by daviddias** [libp2p/research-pubsub#10]
> Notes from the call 
> - We need to figure out a way to spawn a lot of long-running nodes; hundreds, potentially THOUSANDS. Begin with your machine: "Hey, I want to spawn _n_ nodes in my machine". 
> - These nodes will have to be non-IPFS nodes, just libp2p. 
> - You could use Kubernetes for this.
> - We need this asap in order to test our design decisions
> - Deploying and clustering can be separated out. You need a way to control the cluster, in addition to spawning and deploying nodes.

**Comment by gavinmcdermott** [comment]
Thanks for posting—I also recalled something about:
- Bitswap having a script to spin up nodes
- go-ipfs having something for this purpose _(was it IPTB?)_

_Any clarifications or links to relevant repos would helpful_

Since the harness is a must have for people to implement and test scenarios, and for my own (selfish) purposes of diving into libp2p and getting myself familiar with the ecosystem, I'd be happy to take a run at building the initial test harness to keep things moving forward (though there may be a couple questions along the way). 

@diasdavid : I thought it was mentioned that you might take a crack at this, but it also sounds like there is a lot going on. So if this isn't duplicating efforts or working on something that you intended to do, I'd be happy to get this going. Let me know!

**Comment by diasdavid** [comment]
IPTB exists for go-ipfs, but here we would be shooting for a straight network of libp2p nodes. Here is the repo https://github.com/whyrusleeping/iptb

I've created this script for bitswap -- https://github.com/ipfs/js-ipfs-bitswap/blob/master/test/utils.js#L96 -- that can be repurposed, because it is essentially spawning libp2p nodes, JavaScript ones though :)

@gavinmcdermott thank you for volunteering, that would be excellent! I'm happy to review and provide help with support, as human documentation or with code at any time.

**Comment by Kubuxu** [comment]
As you want to spawn much more nodes that we usually do in go-ipfs, you would have to go for something lighter, maybe clustered approach:

Multiple nodes (few hundreds) inside one process (node or go) and then some of them can connect to the outside, with other clusters like that.

IPTB creates full go-ipfs nodes and has few options for separating them: none or docker.
For a long time I am planning to implement network namespaces separation option but I haven't time do do it, it would have benefits of docker separation with no additional overhead.

It is also quite important to simulate real world quite accurately if you want to use it for testing, this means latency, packet drop and **nodes going up and down**, this is something that we missed during work on cjdns (which is written in C and we were able to create networks of millions of nodes during tests) and it turned out that our path searching implementation has some problems with that. Only after about 2k nodes joined real world network we started seeing those problems.

**Comment by gavinmcdermott** [comment]
Thanks for sharing @Kubuxu, much appreciated.

**Comment by jbenet** [comment]
I would also look at kubernetes, that has all the clustering that we may
want to do, I think.

cc @hermanjunge as he may be interested in this too. He is doing this for
ipfs-cluster

**Comment by hermanjunge** [comment]
How can I be of help?

**Comment by gavinmcdermott** [comment]
@hermanjunge, gracias. Feel free to email me  so we can sync up and keep any unrelated spam off the thread.

**Comment by gavinmcdermott** [comment]
**Update:** [This repo](https://github.com/gavinmcdermott/pubsub_testnet) has the latest. Currently you can use it to spin up a testnet instance of a specified size and topology (More topologies are being added this week). I am also hopefully talking with @hermanjunge about containers this week. With these basics wrapped up soon, I think we'll have something useful for the community.

I'll keep `testnet` dev conversations in the aforementioned repo, but I'll continue posting relevant updates here as they occur. For anyone who wants to help move the ball forward on this, please drop me an email -or- check out [recent issues](https://github.com/gavinmcdermott/pubsub_testnet/issues) for updates / entry points.
